---
# Variables globales
ansible_user: debian
ssh_port: 22
ansible_ssh_private_key_file: ~/.ssh/iac_soutenance
# TODO jour 3+ : politique de durcissement partagée
ansible_ssh_common_args: >-
  -o IdentitiesOnly=yes
  {% if inventory_hostname != 'bastion' %}
  -o ProxyJump=debian@{{ hostvars['bastion']['ansible_host'] }}
  {% endif %}