---
# Playbook principal : applique la configuration puis le durcissement.
- name: Configuration de base + durcissement
  hosts: all
  become: true
  roles:
    - { role: common, tags: [common] }
    - { role: ssh_hardening, tags: [ssh_hardening] }
    - { role: firewall, tags: [firewall] }
    - { role: cis_hardening, tags: [cis_hardening] }
    - { role: monitoring, tags: [monitoring] }   # implémenté jour 9 : node_exporter       

- name: Serveur web
  hosts: web
  become: true
  roles:
    - web              # implémenté jour 6

- name: Base de données
  hosts: db
  become: true
  roles:
    - db               # implémenté jour 6
